### PR TITLE
#Form Added To Portfolio setup

### PR DESCRIPTION
**Pull request by helina42**
## This project includes:

- HTML and CSS for a portfolio page
- It includes work detail section and about me section
- This project was created with major use of Flex box.
- Form Added To Portfolio  and styled

### CODE REVIEW

**Review by Zuhaib042 — COMMENTED** [review]
Hi @helina42 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't have the proper files needed to get reviewed. for example you dont have index.html so kindly consider adding index.html file to your pull request and then asked for a review.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by helina42** [comment]
@Zuhaib042  hi,
I can see the index.html file on my file. Kindly tell me how to fix the error you see?

**Comment by helina42** [comment]
Please check my main branch I have merged my codes to my main branch therefore my html file is on my main.

**Review by topeogunleye — COMMENTED** [review]
Hi @helina42, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Merged and Deleted Pull Request ⚠️

- Pull request is merged and deleted. Please do not submit a merged and deleted pull request for review. Kindly revert your merging and deletion or create a new repo for your project.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

>Invalid Code Review Request **does not count** into the code reviews limit.

**Comment by helina42** [comment]
Please kindly check my main branch, for this project because my project file (my html file is on my main).
I have reverted all my merge and deleted branches as requested.

**Comment by topeogunleye** [comment]
> Please kindly check my main branch, for this project because my project file (my html file is on my main). I have reverted all my merge and deleted branches as requested.

@helina42, you haven't reverted your merge and also your partner hasn't contributed and this is a pair programming project. Your pair programming projects will be invalidated if your partner does not contribute

**Comment by helina42** [comment]
@topeogunleye I have collaborated with my partner on the project but due to lots of branches a being created the track seems to be messed up I think. How should I fix things after this. I have clicked on revert on my merges but I think its still now working.

**Review by topeogunleye — COMMENTED** [review]
Hi @helina42, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request ⚠️

   - You have submitted a pair programming project with no contributions from your partner.  Kindly report any issue you had with your partner to the student's success team and they'll permit you to work solo or look for a suitable partner.
  
## Merged Pull Request ⚠️

- Pull request is merged and deleted. Please do not submit a merged pull request for review. Kindly revert your merging or create a new pull request for your project.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

>Invalid Code Review Request **does not count** into the code reviews limit.

**Comment by topeogunleye** [comment]
> @topeogunleye I have collaborated with my partner on the project but due to lots of branches a being created the track seems to be messed up I think. How should I fix things after this. I have clicked on revert on my merges but I think its still now working.

@helina42, Please kindly read the GitHub docs on how to revert a [pull request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/reverting-a-pull-request)

When you revert your merge, if it open's a new pull request, add a link to this PR in the description of the new PR. Also ensure your partner makes new commits on this pull request to ensure your pull request is valid.

**Pull request merged**
